version: '3'
services:
  api:
    image: ${IMAGE_NAME}/api:latest
    deploy:
      replicas: 1
      labels:
        xyz.tangerie.reverse_proxy.path: "/dexter/api"
        xyz.tangerie.reverse_proxy.port: "80"
    networks:
      - default
      - nginx-proxy-overlay
    environment:
      - DEXCOM_ENV_FILE=/run/secrets/DexcomAuth
      - DB_PATH=/data/dexter.db
    volumes:
      - dexter-data:/data
    secrets:
      - DexcomAuth

  frontend:
    image: ${IMAGE_NAME}/frontend:latest
    deploy:
      replicas: 1
      labels:
        xyz.tangerie.reverse_proxy.path: "/dexter"
        xyz.tangerie.reverse_proxy.port: "80"
    networks:
      - default
      - nginx-proxy-overlay
    depends_on:
      - api

volumes:
  dexter-data:

networks:
  default:
  nginx-proxy-overlay:
    external: true
    driver: overlay

secrets:
  DexcomAuth:
    external: true