name: Build, Push & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-api:
    uses: TangerieOrg/Workflows/.github/workflows/docker-build-push.yml@main
    with:
      image_name: dexter/api
      registry_name: docker.tangerie.xyz
      path: api
      ref: main
    secrets: inherit

  build-frontend:
      uses: TangerieOrg/Workflows/.github/workflows/docker-build-push.yml@main
      with:
        image_name: dexter/frontend
        registry_name: docker.tangerie.xyz
        path: frontend
        ref: main
      secrets: inherit
    
  deploy:
    uses: TangerieOrg/Workflows/.github/workflows/docker-deploy.yml@main
    needs: 
      - build-api
      - build-frontend
    with:
      image_name: dexter
      registry_name: docker.tangerie.xyz
      
    secrets: inherit